# Generated by Django 2.1.2 on 2018-11-03 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20181103_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationvisit',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='locationvisit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
